apiVersion: v1
kind: Service

metadata:
  name: self-healing-service
  namespace: self-healing

spec:
  selector:
    app: self-healing-app

  ports:
  - port: 5000
    targetPort: 5000

  type: ClusterIP
